# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='random_value',
            field=models.IntegerField(default=132114151231),
            preserve_default=False,
        ),
    ]
